### ISSUE TITLE
add to Julia benchmarks collection?

### ISSUE THREAD

**Issue by StefanKarpinski** [Enet4/julia-bench-rs#1]
Nice results! Might as well collect more implementations in the original location. Should probably move that out of the main Julia repo at some point, but that's a separate issue.

**Comment by Enet4** [comment]
Yes, that is a great idea and I'm willing to collaborate. :) Not sure about this weekend, but given the interest, I'll seek to make a pull request during the next week.

**Comment by StefanKarpinski** [comment]
No hurry, but it would be a welcomed contribution. Later we can move it out into a separate repo.

**Comment by Enet4** [comment]
https://github.com/JuliaLang/julia/pull/22433

**Comment by Enet4** [comment]
Now that there is a dedicated repository for the benchmarks, I sent a new PR: https://github.com/JuliaLang/Microbenchmarks/pull/1

**Comment by Enet4** [comment]
The benchmark is in! :tada: I will seek to keep the upstream version updated every once in a sufficiently big while. Thank you for your collaboration.
